name: 'Check License or Date from github PR files'
description: 'Check License or Date from github PR files'
inputs:
  token:
    description: 'Github Token'
    required: true
  config-path:
    description: 'Specify license-check.json path'
    required: false
  commit-from:
    description: 'specify the start of commit hash'
    required: false
  commit-to:
    description: 'specify the end of commit hash'
    required: false
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'main.js'
branding:
  icon: 'check'
  color: 'green'
